"""Auto-loader for database schema and table descriptions.

This module automatically:
1. Connects to SQLite database and reads table names and columns
2. Loads descriptions from sqlite_table_descriptions.json (generated by sqlite_table_description.py)
3. Optionally loads tableinfos/ directory with individual table summaries
4. Merges all information with priority: detailed descriptions > tableinfos > empty string

Usage (as CLI):
    python db_schema_loader.py --db_path /path/to/db.db --descriptions sqlite_table_descriptions.json

Usage (from Python - Simple Auto Mode):
    from db_schema_loader import auto_load_database
    table_names, table_infos, table_columns = auto_load_database()
    # Automatically finds database and descriptions in current directory

Usage (from Python - Manual Mode):
    from db_schema_loader import load_table_info
    table_infos, table_columns = load_table_info(db_path, descriptions_path)
"""
from __future__ import annotations

import argparse
import json
import os
import glob
from pathlib import Path
from typing import Dict, List, Tuple, Optional

from sqlalchemy import create_engine, inspect, text


def normalize_db_path(path: str) -> str:
    """Normalize path and remove stray colons used in your environment naming.

    The original project used filenames with a colon like ':my_database_mimic.db'.
    We remove any stray leading colons to get a usable filesystem path.
    """
    p = os.path.expanduser(os.path.expandvars(path))
    # Strip stray colon characters that some earlier scripts used in DB names
    dirname, basename = os.path.split(p)
    safe_basename = basename.replace(":", "")
    return os.path.abspath(os.path.join(dirname or ".", safe_basename))


def find_database_file(search_dir: str = ".") -> Optional[str]:
    """Auto-discover SQLite database file in the given directory.
    
    Args:
        search_dir: Directory to search for database files (default: current directory)
    
    Returns:
        Path to the first .db file found, or None if not found
    """
    search_patterns = [
        os.path.join(search_dir, "*.db"),
        os.path.join(search_dir, "**/*.db"),
    ]
    
    for pattern in search_patterns:
        matches = glob.glob(pattern, recursive=False)
        if matches:
            # Prefer files with 'mimic' or 'database' in name
            priority = [m for m in matches if 'mimic' in m.lower() or 'database' in m.lower()]
            if priority:
                return priority[0]
            return matches[0]
    
    return None


def find_description_file(search_dir: str = ".") -> Optional[str]:
    """Auto-discover table description JSON file.
    
    Args:
        search_dir: Directory to search for description files
    
    Returns:
        Path to description file, or None if not found
    """
    candidates = [
        os.path.join(search_dir, "sqlite_table_descriptions.json"),
        os.path.join(search_dir, "table_descriptions.json"),
        os.path.join(search_dir, "descriptions.json"),
    ]
    
    for candidate in candidates:
        if os.path.exists(candidate):
            return candidate
    
    return None


def load_local_descriptions(path: str) -> Dict[str, str]:
    """Load a JSON file mapping table name -> description.

    The JSON is expected to be a simple mapping, e.g.
      {"ADMISSIONS": "Admissions table...", "PATIENTS": "..."}

    If the file is missing or invalid, returns empty dict.
    """
    if not path:
        return {}
    p = Path(path)
    if not p.exists():
        return {}

    try:
        with p.open("r", encoding="utf-8") as fh:
            data = json.load(fh)
            if not isinstance(data, dict):
                return {}
            # Normalize keys to their original case as stored in DB (don't upper-case)
            return {k: str(v) for k, v in data.items()}
    except Exception as e:
        print(f"Warning: Failed to load descriptions from {path}: {e}")
        return {}


def load_tableinfos_directory(tableinfos_dir: str = "tableinfos") -> Dict[str, str]:
    """Load table summaries from tableinfos/ directory.
    
    Each file should be named like "0_PATIENTS.json" and contain:
    {"table_name": "PATIENTS", "table_summary": "..."}
    
    Args:
        tableinfos_dir: Path to tableinfos directory
    
    Returns:
        Dictionary mapping table name to summary
    """
    summaries = {}
    
    if not os.path.exists(tableinfos_dir):
        return summaries
    
    for filename in os.listdir(tableinfos_dir):
        if not filename.endswith('.json'):
            continue
        
        filepath = os.path.join(tableinfos_dir, filename)
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                data = json.load(f)
                if 'table_name' in data and 'table_summary' in data:
                    summaries[data['table_name']] = data['table_summary']
        except Exception as e:
            print(f"Warning: Failed to load {filepath}: {e}")
    
    return summaries


def load_table_info(
    db_path: str, 
    descriptions_path: Optional[str] = None,
    tableinfos_dir: Optional[str] = None
) -> Tuple[Dict[str, str], Dict[str, List[str]]]:
    """Return (table_names_and_infos, table_names_and_columns) loaded from DB and local descriptions.

    - table_names_and_infos: mapping table_name -> description (string)
    - table_names_and_columns: mapping table_name -> list of column names

    The function does NOT call OpenAI; it uses local descriptions only. If a
    table has no description in the file, description is set to an empty string.
    
    Args:
        db_path: Path to SQLite database file
        descriptions_path: Path to sqlite_table_descriptions.json (optional)
        tableinfos_dir: Path to tableinfos/ directory (optional)
    
    Returns:
        Tuple of (table_descriptions, table_columns)
    """
    db_path_norm = normalize_db_path(db_path)
    engine = create_engine(f"sqlite:///{db_path_norm}")

    # Load descriptions from main description file
    local_desc = load_local_descriptions(descriptions_path) if descriptions_path else {}
    
    # Load summaries from tableinfos directory (as fallback)
    tableinfo_summaries = {}
    if tableinfos_dir:
        tableinfo_summaries = load_tableinfos_directory(tableinfos_dir)

    inspector = inspect(engine)

    table_names_and_infos: Dict[str, str] = {}
    table_names_and_columns: Dict[str, List[str]] = {}

    try:
        tables = inspector.get_table_names()
    except Exception:
        tables = []

    for tbl in tables:
        # Get columns from database
        cols: List[str] = []
        try:
            cols_info = inspector.get_columns(tbl)
            cols = [c["name"] for c in cols_info]
        except Exception:
            # If inspection fails for this table, leave columns empty
            cols = []

        # Priority: detailed descriptions > tableinfo summaries > empty string
        desc = local_desc.get(tbl)
        if desc is None:
            desc = local_desc.get(tbl.upper())
        if not desc:
            desc = tableinfo_summaries.get(tbl, "")

        table_names_and_columns[tbl] = cols
        table_names_and_infos[tbl] = desc or ""

    return table_names_and_infos, table_names_and_columns


def auto_load_database(
    search_dir: str = ".",
    db_path: Optional[str] = None,
    descriptions_path: Optional[str] = None,
    tableinfos_dir: Optional[str] = None
) -> Tuple[List[str], Dict[str, str], Dict[str, List[str]]]:
    """Automatically discover and load database with descriptions.
    
    This is the main convenience function that handles all the auto-discovery.
    
    Args:
        search_dir: Directory to search for database and descriptions (default: current)
        db_path: Explicit path to database (optional, will auto-discover if not provided)
        descriptions_path: Explicit path to descriptions (optional, will auto-discover)
        tableinfos_dir: Path to tableinfos directory (optional)
    
    Returns:
        Tuple of (table_names, table_descriptions, table_columns)
        - table_names: List of table names
        - table_descriptions: Dict mapping table name to description
        - table_columns: Dict mapping table name to list of column names
    """
    print("=" * 60)
    print("Auto-loading Database Schema and Descriptions")
    print("=" * 60)
    
    # Auto-discover database if not provided
    if not db_path:
        db_path = find_database_file(search_dir)
        if not db_path:
            raise FileNotFoundError(f"No database file found in {search_dir}")
        print(f"✓ Found database: {db_path}")
    else:
        print(f"✓ Using database: {db_path}")
    
    # Auto-discover descriptions if not provided
    if not descriptions_path:
        descriptions_path = find_description_file(search_dir)
        if descriptions_path:
            print(f"✓ Found descriptions: {descriptions_path}")
        else:
            print(f"⚠ No descriptions file found in {search_dir}")
    else:
        print(f"✓ Using descriptions: {descriptions_path}")
    
    # Auto-discover tableinfos directory
    if not tableinfos_dir:
        candidate = os.path.join(search_dir, "tableinfos")
        if os.path.exists(candidate):
            tableinfos_dir = candidate
            print(f"✓ Found tableinfos directory: {tableinfos_dir}")
    
    # Load table info
    table_infos, table_columns = load_table_info(
        db_path, 
        descriptions_path,
        tableinfos_dir
    )
    
    table_names = list(table_columns.keys())
    
    print(f"\n✓ Loaded {len(table_names)} tables from database")
    print(f"✓ Found descriptions for {sum(1 for v in table_infos.values() if v)} tables")
    print("\nTables found:")
    for i, table in enumerate(table_names, 1):
        has_desc = "✓" if table_infos[table] else "○"
        print(f"  {i:2d}. {has_desc} {table} ({len(table_columns[table])} columns)")
    
    print("=" * 60)
    
    return table_names, table_infos, table_columns


def _cli():
    parser = argparse.ArgumentParser(description="Auto-load database schema and descriptions")
    parser.add_argument(
        "--db_path", 
        required=False, 
        help="Path to sqlite DB file (auto-discovers if not provided)"
    )
    parser.add_argument(
        "--descriptions", 
        required=False, 
        help="Path to sqlite_table_descriptions.json (auto-discovers if not provided)"
    )
    parser.add_argument(
        "--tableinfos_dir",
        required=False,
        help="Path to tableinfos directory (auto-discovers if not provided)"
    )
    parser.add_argument(
        "--search_dir",
        default=".",
        help="Directory to search for database and descriptions (default: current directory)"
    )
    args = parser.parse_args()

    # Use auto_load_database for convenience
    table_names, table_infos, table_columns = auto_load_database(
        search_dir=args.search_dir,
        db_path=args.db_path,
        descriptions_path=args.descriptions,
        tableinfos_dir=args.tableinfos_dir
    )
    
    print(f"\n✓ Successfully loaded {len(table_names)} tables!")


if __name__ == "__main__":
    _cli()
